name = "colours"
description = "A Gleam library for adding colours in terminal outputs."

version = "0.1.2"

licences = ["MIT"]

[repository]
type = "github"
user = "Willyboar"
repo = "colours"

[dependencies]
gleam_stdlib = "~> 0.28"

[dev-dependencies]
gleeunit = "~> 0.10"
